apiVersion: v1
kind: Service
metadata:
  name: master-server
  labels:
    app: master-server
spec:
  selector:
    app: master-server
  ports:
  - port: 7000
    targetPort: 7000
    name: tcp
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-server
  labels:
    app: master-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master-server
  template:
    metadata:
      labels:
        app: master-server
    spec:
      containers:
      - name: master-server
        image: localhost:5000/master-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          tcpSocket:
            port: 7000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 7000
          initialDelaySeconds: 5
          periodSeconds: 10 