apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: applications
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: gs-template-repo
  path: ./flux/apps/overlays/dev
  prune: true # Automatically remove resources that are no longer present in Git
  wait: true # Wait for resources to be ready before proceeding
