apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gs-template-repo
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/mbastakis/gstemplatelayout
  ref:
    branch: main
